#!/bin/bash

echo "Reversing Activator root support using sudo..."
echo "Restoring from old sudo file..."
cp -a /etc/sudoers /etc/SystemHostsBlocker/Sudo/sudoers
cp -a /etc/SystemHostsBlocker/Sudo/origSudo /etc/sudoers
chmod 0400 /etc/sudoers
chown root:staff /etc/sudoers
echo "Done!"
