#!/bin/bash

echo "Overwriting old hosts file..."
cp -a /etc/SystemHostsBlocker/systemhosts /etc/hosts
echo "Fixing permissions..."
chmod 644 /etc/hosts /etc/SystemHostsBlocker/ /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
chown root:wheel /etc/hosts /etc/SystemHostsBlocker/ /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
echo "Killing discoveryd/mDNSResponder..."
killall -9 discoveryd
killall -9 mDNSResponder
echo "The daemons should have died and restarted by now..."
echo "Enjoy an ad free iOS with SystemHostsBlocker!"
echo "Still ads somewhere? Please let me know if you find any ads or broken sites!"
exit 0
