#!/bin/bash

echo "Copyright Nathan Goodwin 2016-2017."
echo "Starting install of SystemHostsBlocker for iOS 10.2 and below."

iosVersion=$(sw_vers -productVersion)

if [ "$iosVersion" ≤ "10.2" ]
then
    echo "You're on a supported version ($iosVersion). Installing."
else
    echo "You're on a version ($iosVersion) that is currently not supported. Check for an update soon!"
		&& exit
fi

echo "Checking if stash already exists..."
file="/etc/SystemHostsBlocker/StashedHosts/originalhosts"
if [ -f "$file" ]
then
	echo "$file found. Running update. Not stashing."
  echo "Overwriting old hosts file..."
  cp -a /etc/SystemHostsBlocker/systemhosts /etc/hosts
  echo "Fixing permissions..."
  chmod 644 /etc/hosts /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
  chown root:wheel /etc/hosts /etc/SystemHostsBlocker/ /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
  echo "Killing discoveryd/mDNSResponder..."
  killall -9 discoveryd
  killall -9 mDNSResponder
  echo "The daemons should have died and restarted by now..."
	echo "Getting host line ammount..."
	lines=$(cat /etc/hosts | wc -l)
	echo "Your hosts file now has $lines lines!"
  echo "Enjoy an ad free iOS with SystemHostsBlocker!"
  echo "Still ads somewhere? Please let me know if you find any ads or broken sites!"
  exit 0

else
	echo "$file not found. Stashing."
  echo "Stashing old hosts file..."
  mkdir /etc/SystemHostsBlocker/StashedHosts
  cp -a /etc/hosts /etc/SystemHostsBlocker/StashedHosts/originalhosts
  chmod 644 /etc/SystemHostsBlocker/StashedHosts/originalhosts
  chown root:wheel /etc/SystemHostsBlocker/StashedHosts/originalhosts
  echo "Stashing old hosts file complete..."
  echo "Running installer..."
  echo "Overwriting old hosts file..."
  cp -a /etc/SystemHostsBlocker/systemhosts /etc/hosts
  echo "Fixing permissions..."
  chmod 644 /etc/hosts /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
  chown root:wheel /etc/hosts /etc/SystemHostsBlocker/ /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
  echo "Killing discoveryd/mDNSResponder..."
  killall -9 discoveryd
  killall -9 mDNSResponder
  echo "The daemons should have died and restarted by now..."
	echo "Getting host line ammount..."
	lines=$(cat /etc/hosts | wc -l)
	echo "Your hosts file now has $lines lines!"
  echo "Enjoy an ad free iOS with SystemHostsBlocker!"
  echo "Still ads somewhere? Please let me know if you find any ads or broken sites!"
  exit 0
fi
