#!/bin/bash

if [[ $1 == remove ]]; then

echo "Restoring stashed host file..."
cp -a /etc/StashedHosts/originalhosts /etc/hosts
echo "Restore completed. Fixing permissions..."
chmod 644 /etc/hosts
chown root:wheel /etc/hosts
echo "Fixed permissions."
echo "Killing discoveryd/mDNSResponder..."
killall -9 discoveryd
killall -9 mDNSResponder
echo "The Daemons should have died and restarted by now..."
echo "Cleaning up the mess..."
rm -rf /etc/SystemHostsBlocker
rm -rf /etc/StashedHosts
echo "You should be reset back to the stashed hosts file now!"
exit 0

else

exit 0

fi
