#!/bin/bash

if [[ $1 == remove ]]; then

echo "Restoring Default Hosts File"
cp -a /etc/BackupHosts/originalhosts /etc/hosts
echo "Restore Complete"
chown root:wheel /etc/hosts
chmod 644 /etc/hosts
echo "Killing discoveryd/mDNSResponder..."
killall -9 discoveryd
killall -9 mDNSResponder
echo "Should have died and restarted by now..."
echo "Cleaning up the mess..."
rm -rf /etc/SystemHostsBlocker
rm -rf /etc/BackupHosts
echo "You should be reset back to the default hosts file now!"
exit 0

else

exit 0

fi
