#!/bin/bash

echo "Copyright Nathan Goodwin 2016-2017."
echo "Starting install of SystemHostsBlocker for amd64 Linux Systems"

echo "Checking if stash already exists..."
file="/etc/SystemHostsBlocker/StashedHosts/originalhosts"
if [ -f "$file" ]
then
	echo "$file found. Running update. Not stashing."

	blines=$(cat /etc/hosts | wc -l)
	echo "Before update, you have $blines lines in your hosts file."
  echo "Overwriting old hosts file..."
  cp -a /etc/SystemHostsBlocker/systemhosts /etc/hosts
  echo "Fixing permissions..."
  chmod 644 /etc/hosts /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
	echo "Getting host line ammount..."
	lines=$(cat /etc/hosts | wc -l)
	echo "Your hosts file now has $lines lines!"
  echo "Enjoy an ad free iOS with SystemHostsBlocker!"
  echo "Still ads somewhere? Please let me know if you find any ads or broken sites!"

  exit 0

else
	echo "$file not found. Stashing."
  echo "Stashing old hosts file..."
  mkdir /etc/SystemHostsBlocker/StashedHosts
  cp -a /etc/hosts /etc/SystemHostsBlocker/StashedHosts/originalhosts
  chmod 644 /etc/SystemHostsBlocker/StashedHosts/originalhosts
  chown root:wheel /etc/SystemHostsBlocker/StashedHosts/originalhosts
  echo "Stashing old hosts file complete..."

  echo "Running installer..."
	blines=$(cat /etc/hosts | wc -l)
	echo "Before installing, you have $blines lines in your hosts file."
  echo "Overwriting old hosts file..."
  cp -a /etc/SystemHostsBlocker/systemhosts /etc/hosts
  echo "Fixing permissions..."
  chmod 644 /etc/hosts /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
	echo "Getting host line ammount..."
	lines=$(cat /etc/hosts | wc -l)
	echo "Your hosts file now has $lines lines!"
  echo "Enjoy an ad free iOS with SystemHostsBlocker!"
  echo "Still ads somewhere? Please let me know if you find any ads or broken sites!"

  exit 0
fi
