#!/bin/bash

echo "Enabling Activator root support using sudo..."
echo "Backing up old sudo file..."
cp -a /etc/sudoers /etc/SystemHostsBlocker/Sudo/origSudo
echo "Backed up old sudoers file..."
echo "Writing custom file..."
cp -a /etc/SystemHostsBlocker/Sudo/sudoers /etc/sudoers
chmod 0400 /etc/sudoers
echo "Done! To reverse changes, run 'ractivator'"
