#!/bin/bash

echo "Running this script will backup your sudoers file and rewrite my own. Running the script ./ractivator or uninstalling will reverse this."

echo "Running MD5Sum Check..."
echo "Moving to script directory..."
cd /etc/SystemHostsBlocker/
echo "Moved to directory..."
echo "Starting check..."
if md5sum -c etc/SystemHostsBlocker/Security/activator.md5; then
    echo "Heck yeah! Your files were verified! Continuing to run script!"
else
    echo "We couldn't verify this script is genuine. It may have been tempered with. Exit." exit
fi

echo "Enabling Activator root support using sudo..."
echo "Backing up old sudo file..."
cp -a /etc/sudoers /etc/SystemHostsBlocker/Sudo/origSudo
echo "Backed up old sudoers file..."
echo "Writing custom file..."

echo "Appending custom entries to sudoers file..."
echo "mobile ALL=(root) NOPASSWD:/etc/SystemHostsBlocker/enable" >> /etc/sudoers
echo "mobile ALL=(root) NOPASSWD:/etc/SystemHostsBlocker/disable" >> /etc/sudoers
echo "mobile ALL=(root) NOPASSWD:/etc/SystemHostsBlocker/restore" >> /etc/sudoers
echo "mobile ALL=(root) NOPASSWD:/etc/SystemHostsBlocker/stash" >> /etc/sudoers
echo "Done Appending!"



echo "Running last security step..."
chown root:wheel /etc/SystemHostsBlocker/activator /etc/SystemHostsBlocker/enable /etc/SystemHostsBlocker/disable /etc/SystemHostsBlocker/ractivator /etc/SystemHostsBlocker/restore /etc/SystemHostsBlocker/stash /etc/SystemHostsBlocker/systemhosts /etc/SystemHostsBlocker/Sudo/sudoers
echo "All done!"