#!/bin/bash

echo "Attempting to disable System Hosts Blocker..."
echo "Make sure to run as root."

echo "Creating Stash2 (For running enable script.)"
cp -a /etc/hosts /etc/SystemHostsBlocker/StashedHosts/stash2
chmod 644 /etc/SystemHostsBlocker/StashedHosts/stash2
chown root:wheel /etc/SystemHostsBlocker/StashedHosts/stash2

echo "Restoring to stashed hosts..."
cp -a /etc/SystemHostsBlocker/StashedHosts/originalhosts /etc/hosts
echo "Restore completed. Fixing permissions..."
chmod 644 /etc/hosts
chown root:wheel /etc/hosts
echo "Done!"
