#!/bin/bash

echo "Attempting to enable System Hosts Blocker..."
echo "Make sure to run as root."

echo "Restoring to SHB hosts..."
echo "Overwriting old hosts file..."
cp -a /etc/SystemHostsBlocker/StashedHosts/stash2 /etc/hosts
chmod 644 /etc/hosts
chown root:wheel /etc/hosts
echo "Done!"

exit