#!/bin/bash

echo "Running MD5Sum Check..."
echo "Moving to script directory..."
cd /etc/SystemHostsBlocker/
echo "Moved to directory..."
echo "Starting check..."
if md5sum -c etc/SystemHostsBlocker/Security/ractivator.md5; then
    echo "Heck yeah! Your files were verified! Continuing to run script!"
else
    echo "We couldn't verify this script is genuine. It may have been tempered with. Exit." exit
fi

echo "Un-appending lines from Sudoers file..."
sed -i '/mobile ALL=(root) NOPASSWD:/etc/SystemHostsBlocker/enable/d' /etc/sudoers
sed -i '/mobile ALL=(root) NOPASSWD:/etc/SystemHostsBlocker/disable/d' /etc/sudoers
sed -i '/mobile ALL=(root) NOPASSWD:/etc/SystemHostsBlocker/restore/d' /etc/sudoers
sed -i '/mobile ALL=(root) NOPASSWD:/etc/SystemHostsBlocker/stash/d' /etc/sudoers
echo "Should be done now!"

echo "Running last security step..."
chown root:wheel /etc/SystemHostsBlocker/activator /etc/SystemHostsBlocker/enable /etc/SystemHostsBlocker/disable /etc/SystemHostsBlocker/ractivator /etc/SystemHostsBlocker/restore /etc/SystemHostsBlocker/stash /etc/SystemHostsBlocker/systemhosts /etc/SystemHostsBlocker/Sudo/sudoers
echo "All done!"