#!/bin/bash

echo "Attempting to restore to original hosts file..."
echo "Make sure to run as root."

echo "Running MD5Sum Check..."
echo "Moving to script directory..."
cd /etc/SystemHostsBlocker/
echo "Moved to directory..."
echo "Starting check..."
if md5sum -c etc/SystemHostsBlocker/Security/restore.md5; then
    echo "Heck yeah! Your files were verified! Continuing to run script!"
else
    echo "We couldn't verify this script is genuine. It may have been tempered with. Exit." exit
fi

echo "Restoring to default hosts..."
echo "Overwriting current hosts file..."
cp -a /etc/SystemHostsBlocker/defaulthosts /etc/hosts
chmod 644 /etc/hosts /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
chown root:wheel /etc/hosts /etc/SystemHostsBlocker/ /etc/SystemHostsBlocker/defaulthosts /etc/SystemHostsBlocker/systemhosts
echo "Done!"
echo "You'll need to run the enable script to restore functionality."

echo "Running last security step..."
chown root:wheel /etc/SystemHostsBlocker/activator /etc/SystemHostsBlocker/enable /etc/SystemHostsBlocker/disable /etc/SystemHostsBlocker/ractivator /etc/SystemHostsBlocker/restore /etc/SystemHostsBlocker/stash /etc/SystemHostsBlocker/systemhosts /etc/SystemHostsBlocker/Sudo/sudoers
echo "All done!"

exit